config/routes.rb
FirstApp::Application.routes.draw do
 
  devise_for :users

  get "bills/create"

  resources :products


  root :to => 'welcome#index', :as => :index
  match 'about' => 'welcome#about', :as => :about
  match 'contact' => 'welcome#contact', :as => :contact
  match 'black' => 'welcome#black', :via => :get, :as => :black

  resources :users do
    resources :bills
  end

  match 'change_locale/:locale' => 'welcome#change_locale', :as => :change_locale  
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :name, :description, :user_id, :date, :value

  validates :name, :presence => true, :allow_blank => false
  validates :user_id, :presence => true
  validates :date, :presence => true
  validates :value, :presence => true

  belongs_to :user

  default_scope order("bills.date DESC")
  scope :recents, order("bills.date DESC").limit(5)
  scope :recents_by_date, lambda {|date|
    where ("bills.date <= '#{date.strftime('%Y-%m-%d %H:%M:%S.000000')}'")
  }
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :quantity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :email, :age, :gender

  MALE = 1
  FEMALE = 2
  OTHER = 3

  validates :name, :presence => true, :allow_blank => false
  validates :email, :presence => true, :allow_blank => false
  validates_uniqueness_of :email
  validates :gender, :presence => true, :if => :adulthood
  
  has_many :bills, :dependent => :destroy

  def adulthood
    self.age.present? and age >= 18
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def create
    @bill = Bill.new(params[:bill])
    flash[:notice] = (@bill.save ? t('saved_successfully') : t('error_while_saving'))
  end

  def destroy 
    @bill = Bill.find(params[:id])
    @bill.destroy
  end

  def edit
    @bill = Bill.find(params[:id])
  end 

  def update
    @bill = Bill.find(params[:id])
    flash[:notice] = (@bill.update_attributes(params[:bill]) ? t('updated_successfully') : t('error_while_updating'))
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -**
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new 
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Usuário criado"
      redirect_to user_path(@user)
    else
      render :action => :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Usuário modificado"
      redirect_to user_path(@user)
    else
      render :action => :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    flash[:notice] = (@user.destroy ? "Usuário deletado" : "Falha na remoção")
    redirect_to users_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery
  before_filter :authenticate_user!, :except => [:index, :about, :contact]

  #layout 'application_black', :only => :black

  def index
  end

  def black
  	render :layout => 'application_black'
  end

  def about
  end

  def contact
  end

  def change_locale
    I18n.locale = params[:locale] 
    redirect_to index_path(:locale => params[:locale])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/application_helper_helper.rb
module ApplicationHelperHelper
  def bootstrap_alert(type)
    html = <<-HTML
      <div class="alert #{ type }">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        #{notice}
      </div>
    HTML
    html.html_safe
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/bills/_index.html.erb
<hr>
<h4><%= t('bills') %></h4>
<% if bills.any? %>
  <% bills.each do |bill| %>
    <div id='bill_<%= bill.id %>' class='well well-small'>
      <h4><%= bill.name %></h4>
      <%= bill.description %>
      <h5><%= l(bill.date, :format => :long) %></h5>
      <h3><%= bill.value.round(2) %></h3>
      <%= link_to t('edit'), edit_user_bill_path(bill.user, bill), :class => "btn btn-primary", :remote => true %>
      <%= link_to t('delete'), [bill.user, bill], :remote => true, :method => :delete, :class => "btn btn-danger" %>
    </div>
  <% end %>
<% else %>
  <div class='alert'>
    <%= t('no_bill_registered_to_this_user') %>
  </div>
<% end %>

app/views/bills/_new.html.erb
<hr>
<h4><%= t('new_bill') %></h4>

<%= form_for([user, bill], :remote => true) do |f| %>
  <%= render :partial => 'shared/error_messages', :locals => { :resource => bill } %>
  <%= f.hidden_field :user_id, :value => user.id %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :value %>
  <%= f.text_field :value %>

  <div class='actions'>
    <%= f.submit t('save'), :class => 'btn btn-success' %>
  </div>

<% end %>

app/views/bills/create.html.erb
<h1>Bills#create</h1>
<p>Find me in app/views/bills/create.html.erb</p>

app/views/bills/create.js.erb
<% if @bill.persisted? %>
  $("#bills").html("<%= j(render :partial => 'bills/index', :locals => { :bills => @bill.user.bills }) %>");
  $("#bills").prepend("<%= j bootstrap_alert('alert-info') %>");
  $("#new_bill").html("<%= j(render :partial => 'bills/new', :locals => { :bill => Bill.new, :user => @bill.user } ) %>");
<% else %>
  $("#new_bill").html("<%= j(render :partial => 'bills/new', :locals => { :bill => @bill, :user => @bill.user }) %>");
<% end %> 

app/views/bills/destroy.js.erb
<% if @bill.destroyed? %>
  $("#bill_<%= @bill.id %>").remove();
<% else %>
  $("#bill_<%= @bill.id %>").prepend("<%= t('error_while_deleting') %>");
<% end %>

app/views/bills/edit.js.erb
$("#new_bill").html("<%= j(render :partial => 'bills/new', :locals => { :bill => @bill, :user => @bill.user }) %>");
$('html, body').animate({scrollTop: $("#new_bill").offset().top });

app/views/bills/update.js.erb
<% if @bill.valid? %>
  $("#bills").html("<%= j(render :partial => 'bills/index', :locals => { :bills => @bill.user.bills }) %>");
  $("#bills").prepend("<%= j bootstrap_alert('alert-info') %>");
  $("#new_bill").html("<%= j(render :partial => 'bills/new', :locals => { :bill => Bill.new, :user => @bill.user } ) %>");
<% else %>
  $("#new_bill").html("<%= j(render :partial => 'bills/new', :locals => { :bill => @bill, :user => @bill.user }) %>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render :partial => 'shared/menu_top' %>
  <div class='container-fluid'>
    <div class='row-fluid'>
      <%= yield :sidebar %>
      <%= yield %>
    </div>
    <%= render :partial => 'shared/footer' %>
  </div>

</body>
</html>

app/views/layouts/application_black.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style='background-color:black;'>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.quantity %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @product.quantity %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> erros:</h2>
    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>&copy; Company 2013</p>
</footer>

app/views/shared/_menu_top.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Hands On Rails", index_path, :class => "brand" %>
      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <%= link_to current_user.name, edit_user_registration_path(current_user), :class => "navbar-link" %>
            <%= link_to "<i class='icon-off icon-white'></i>".html_safe, destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "login", new_user_session_path, :class => "btn" %>
          <% end %>
       </p>
        <ul class="nav">
          <li class="active"><%= link_to "Home", index_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Sidebar</li>
      <li class="active"><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li class="nav-header">Sidebar</li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li class="nav-header">Sidebar</li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <%= render :partial => 'shared/error_messages', :locals => { :resource => user } %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.number_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
    <%= link_to "Voltar", users_path, :class => "btn" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h4>Editar usuário</h4>
<%= render :partial => 'form', :locals => { :user => @user } %>

app/views/users/index.html.erb
<% if @users.any? %>
  <table class="table table-bordered">
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to "#{user.name} (#{user.email}), #{user.age} anos", user %>
          <%= link_to "<i class='icon-edit'></i>".html_safe, edit_user_path(user), :class => "btn btn-mini" %>
          <%= link_to "<i class='icon-trash'></i>".html_safe, user, :method => :delete, :class => "btn btn-mini" %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <div class="alert">
    Nenhum usuário cadastrado
  </div>
<% end %>

<%= link_to "Novo usuário", new_user_path, :class=> "btn btn-success" %>

app/views/users/new.html.erb
<h4><%= t('new_user') %></h4>

<%= render :partial => 'form', :locals => { :user => @user } %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p><b>Nome:</b><%= @user.name %></p>
<p><b>email:</b><%= @user.email %></p>
<p><b>Idade:</b><%= @user.age %></p>
<p><b>Sexo:</b><%= @user.gender %></p>

<div id='new_bill'>
  <%= render :partial => 'bills/new', :locals => { :bill => Bill.new, :user => @user } %>
</div>
  
<div id='bills'>
  <%= render :partial => 'bills/index', :locals => { :bills => @user.bills } %>
</div>

<%= link_to 'Edit', edit_user_path(@user), :class => "btn" %>
<%= link_to 'Back', users_path, :class => "btn" %>

app/views/welcome/about.html.erb
<h1>About us</h1>
<h3>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</h3>

app/views/welcome/black.html.erb
<h1>Hello World black</h1>

app/views/welcome/contact.html.erb
<h1>How to find us</h1>
<h3>
Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</h3>

app/views/welcome/index.html.erb
<%= link_to 'Mudar locale', change_locale_path(:locale => params[:locale] =='pt' ? 'en' : 'pt') %>

<div class="span9">
  <% label = "<i class='icon-user'></i>&nbsp;Usuários".html_safe %>
  <%= link_to label, users_path, :class => "btn btn-large" %>
  
  <% label = "<i class='icon-user'></i>&nbsp;Produtos".html_safe %>
  <%= link_to label, products_path, :class => "btn btn-large" %>

</div><!--/span-->

<%= content_for :sidebar do %>
  <%= render :partial => 'shared/sidebar' %>
<% end %>